export interface Company{
  id:number,
  company_name: string,
  ruc: string,
  owner_name: string,
  address: string,
  locality: string,
  city: string,
  first_name:string,
  last_name:string,
  image:string,
  banner_image:string,
  description:string,
  email:string,
  password:string,
  phone:string,
  role : string,
}
