export interface Company{
  id:number,
  companyName: string,
  ruc: string,
  ownerName: string,
  address: string,
  locality: string,
  city: string,
  firstName:string,
  lastName:string,
  image:string,
  bannerImage:string,
  description:string,
  email:string,
  password:string,
  phone:string,
}
